# site settings
title: Becki Baldwin
subtitle: Online Yoga classes, health and wellbeing
email: becki.baldwin@hotmail.co.uk
description:  I strive towards helping other people, whether it be a high intensity class to get your heart pumping and endorphins flowing, or a relaxing yoga and meditation class to centre yourself after a busy week.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: London
state: 
zip_code: 
country: UK
phone: 
permalink: /:title/
future: true


repository: beckibaldwin.github.io/beckibaldwin

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
facebook_url: https://www.facebook.com/Becki.BaldwinPT
instagram_url: https://www.instagram.com/becki.baldwin/
youtube_url: https://www.youtube.com/channel/UCMshwdsmcOciD2k-QWwrJVw

# build settings
markdown: kramdown

sass:
  style: compressed

# sitemap
plugins:
  - jekyll-sitemap
  - jekyll-airtable
  - environment_variables_generator

airtable:
  enable_sync: true
  base_uid: 'appp7C1MblPCnMePn'
  airtable_api_key: ${{ secrets.GH_PAGES_TOKEN }}
  tables:
    - name: 'Use Cases' 
    - name: 'Whitepapers'    
    - name: 'Quotes'
      long_text_columns:
        - 'column name'