source 'https://rubygems.org'

gem 'jekyll'
gem 'github-pages', group: :jekyll_plugins
gem 'jekyll-sitemap', group: :jekyll_plugins
gem 'airtable', group: :jekyll_plugins
gem 'bigdecimal'
gem 'activesupport'
gem 'json'
gem 'jekyll-watch'
gem 'html-proofer'
gem 'commonmarker'

# Neccessary to prevent Jekyll errors. See https://github.com/github/personal-website/issues/166
gem 'faraday', '0.17.3'